site_url : https://asalvadorc.github.io/AD_Ficheros

site_name: AD - Accés a Dades

extra_css:
  - css/extra.css

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png

nav:
- T1. Gestió del Sistema de fitxers:
  - Objectius: AD_T1_Sistema_de_fitxers/objectius.md
  ## - Instal.lació de IntelliJ Idea Ultimate: AD_T1_Sistema_de_fitxers/Idea.md
  - 1. Introducció: AD_T1_Sistema_de_fitxers/1_introducci.md
  - 2. La classe File. Generalitats.:  AD_T1_Sistema_de_fitxers/2_la_classe_file_generalitats.md
  - 3. Funcionalitat de la classe File: AD_T1_Sistema_de_fitxers/3_funcionalitat_de_la_classe_file.md
  - Exercicis: AD_T1_Sistema_de_fitxers/exercicis.md
- T2. Gestió del contingut de fitxers:
    - Objectius: AD_T2_Gesti_del_contingut_de_fitxers/objectius.md 
    - 1 - Magatzems i fluxos de dades: AD_T2_Gesti_del_contingut_de_fitxers/1__magatzems_i_fluxos_de_dades.md 
    - 2 - Manipulació dels fluxos de dades: AD_T2_Gesti_del_contingut_de_fitxers/2__manipulaci_dels_fluxos_de_dades.md
    - 3 - Fluxos decoradors: AD_T2_Gesti_del_contingut_de_fitxers/3__fluxos_decoradors.md
    - 4 - Simplificació en Kotlin: AD_T2_Gesti_del_contingut_de_fitxers/4__simplificaci_en_kotlin.md 
    - Exercicis: AD_T2_Gesti_del_contingut_de_fitxers/exercicis.md  
- T3. Fitxers de diferents formats:
    - Objectius: AD_T3_Fitxers_de_diferents_formats/objectius.md
    - 1.- Fitxers binaris amb formats específics: AD_T3_Fitxers_de_diferents_formats/1_fitxers_binaris_amb_formats_especfics.md
    - 2.- Accés directe a fitxers: AD_T3_Fitxers_de_diferents_formats/2_accs_directe_a_fitxers.md
    - 3.- Seriació d'objectes: AD_T3_Fitxers_de_diferents_formats/3_seriaci_dobjectes.md
    - 4.- Documents XML: AD_T3_Fitxers_de_diferents_formats/4_documents_xml.md 
    - 5.- Documents JSON: AD_T3_Fitxers_de_diferents_formats/5_documents_json.md      
    - Exercicis: AD_T3_Fitxers_de_diferents_formats/exercicis.md     
